
var data = JSON.stringify({
    "Momentum Indicators":[
       {
          "name":"ADX",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"ADXR",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"APO",
          "parameters":[
             {
                "name":"fastperiod",
                "default":12
             },
             {
                "name":"slowperiod",
                "default":26
             },
             {
                "name":"matype",
                "default":0
             }
          ]
       },
       {
          "name":"AROON",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"AROONOSC",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"BOP",
          "parameters":null
       },
       {
          "name":"CCI",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"CMO",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"DX",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"MACD",
          "parameters":[
             {
                "name":"fastperiod",
                "default":12
             },
             {
                "name":"slowperiod",
                "default":26
             },
             {
                "name":"signalperiod",
                "default":9
             }
          ]
       },
       {
          "name":"MACDEXT",
          "parameters":[
             {
                "name":"fastperiod",
                "default":12
             },
             {
                "name":"fastmatype",
                "default":0
             },
             {
                "name":"slowperiod",
                "default":26
             },
             {
                "name":"slowmatype",
                "default":0
             },
             {
                "name":"signalperiod",
                "default":9
             },
             {
                "name":"signalmatype",
                "default":0
             }
          ]
       },
       {
          "name":"MACDFIX",
          "parameters":[
             {
                "name":"signalperiod",
                "default":9
             }
          ]
       },
       {
          "name":"MFI",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"MINUS_DI",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"MINUS_DM",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"MOM",
          "parameters":[
             {
                "name":"timeperiod",
                "default":10
             }
          ]
       },
       {
          "name":"PLUS_DI",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"PLUS_DM",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"PPO",
          "parameters":[
             {
                "name":"fastperiod",
                "default ":12
             },
             {
                "name":"slowperiod",
                "default":26
             },
             {
                "name":"matype",
                "default":0
             }
          ]
       },
       {
          "name":"ROC",
          "parameters":[
             {
                "name":"timeperiod",
                "default":10
             }
          ]
       },
       {
          "name":"ROCP",
          "parameters":[
             {
                "name":"timeperiod",
                "default":10
             }
          ]
       },
       {
          "name":"ROCR",
          "parameters":[
             {
                "name":"timeperiod",
                "default":10
             }
          ]
       },
       {
          "name":"ROCR100",
          "parameters":[
             {
                "name":"timeperiod",
                "default":10
             }
          ]
       },
       {
          "name":"RSI",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"STOCH",
          "parameters":[
             {
                "name":"fastk_period",
                "default":5
             },
             {
                "name":"slowk_period",
                "default":3
             },
             {
                "name":"slowd_period",
                "default":3
             },
             {
                "name":"slowk_matype",
                "default":0
             },
             {
                "name":"slowd_matype",
                "default":0
             }
          ]
       },
       {
          "name":"STOCHF",
          "parameters":[
             {
                "name":"fastk_period",
                "default":5
             },
             {
                "name":"fastd_period",
                "default":3
             },
             {
                "name":"fastd_matype",
                "default":0
             }
          ]
       },
       {
          "name":"STOCHRSI",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             },
             {
                "name":"fastk_period",
                "default":5
             },
             {
                "name":"fastd_period",
                "default":3
             },
             {
                "name":"fastd_matype",
                "default":0
             }
          ]
       },
       {
          "name":"TRIX",
          "parameters":[
             {
                "name":"timeperiod",
                "default":30
             }
          ]
       },
       {
          "name":"ULTOSC",
          "parameters":[
             {
                "name":"timeperiod1",
                "default":7
             },
             {
                "name":"timeperiod2",
                "default":14
             },
             {
                "name":"timeperiod3",
                "default":28
             }
          ]
       },
       {
          "name":"WILLR",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       }
    ],
    "Overlap Studies":[
       {
          "name":"BBANDS",
          "parameters":[
             {
                "name":"timeperiod",
                "default":5
             },
             {
                "name":"nbdevup",
                "default":2
             },
             {
                "name":"nbdevdn",
                "default":2
             },
             {
                "name":"matype",
                "default":0
             }
          ]
       },
       {
          "name":"DEMA",
          "parameters":[
             {
                "name":"timeperiod",
                "default":30
             }
          ]
       },
       {
          "name":"EMA",
          "parameters":[
             {
                "name":"timeperiod",
                "default":30
             }
          ]
       },
       {
          "name":"HT_TRENDLINE",
          "parameters":null
       },
       {
          "name":"MA",
          "parameters":[
             {
                "name":"timeperiod",
                "default":30
             },
             {
                "name":"matype",
                "default":0
             }
          ]
       },
       {
          "name":"MAMA",
          "parameters":[
             {
                "name":"fastlimit",
                "default":0.5
             },
             {
                "name":"slowlimit",
                "default":0.05
             }
          ]
       },
       {
          "name":"MAVP",
          "parameters":[
             {
                "name":"timeperiod",
                "default":10
             },
             {
                "name":"minperiod",
                "default":2
             },
             {
                "name":"maxperiod",
                "default":30
             },
             {
                "name":"matype",
                "default":0
             }
          ]
       },
       {
          "name":"MIDPOINT",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"MIDPRICE",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"SAR",
          "parameters":[
             {
                "name":"acceleration",
                "default":0.02
             },
             {
                "name":"maximum",
                "default":0.2
             }
          ]
       },
       {
          "name":"SAREXT",
          "parameters":[
             {
                "name":"startvalue",
                "default":0
             },
             {
                "name":"offsetonreverse",
                "default":0
             },
             {
                "name":"accelerationinitlong",
                "default":0.02
             },
             {
                "name":"accelerationlong",
                "default":0.02
             },
             {
                "name":"accelerationmaxlong",
                "default":0.2
             },
             {
                "name":"accelerationinitshort",
                "default":0.02
             },
             {
                "name":"accelerationshort",
                "default":0.02
             },
             {
                "name":"accelerationmaxshort",
                "default":0.2
             }
          ]
       },
       {
          "name":"SMA",
          "parameters":[
             {
                "name":"timeperiod",
                "default":30
             }
          ]
       },
       {
          "name":"T3",
          "parameters":[
             {
                "name":"timeperiod",
                "default":5
             },
             {
                "name":"vfactor",
                "default":0.7
             }
          ]
       },
       {
          "name":"TEMA",
          "parameters":[
             {
                "name":"timeperiod",
                "default":30
             }
          ]
       },
       {
          "name":"TRIMA",
          "parameters":[
             {
                "name":"timeperiod",
                "default":30
             }
          ]
       },
       {
          "name":"WMA",
          "parameters":[
             {
                "name":"timeperiod",
                "default":30
             }
          ]
       }
    ],
    "Volatility Indicators":[
       {
          "name":"ATR",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"NATR",
          "parameters":[
             {
                "name":"timeperiod",
                "default":14
             }
          ]
       },
       {
          "name":"TRANGE",
          "parameters":null
       }
    ],
    "Volume Indicators":[
       {
          "name":"AD",
          "parameters":null
       },
       {
          "name":"ADOSC",
          "parameters":[
             {
                "name":"fastperiod",
                "default":3
             },
             {
                "name":"slowperiod",
                "default":10
             }
          ]
       },
       {
          "name":"OBV",
          "parameters":null
       }
    ]
 })
 
 var json = JSON.parse(data)
 
 var IndicatorData = []
 
 json["Momentum Indicators"].forEach(function(element){
 
    var Indicator = {}
    Indicator.label = element.name
    if (element.parameters != undefined) {
    var IndicatorVar = []
    element.parameters.forEach(function(element){
       IndicatorVar.push(element.default)
    })
    Indicator.variable = IndicatorVar
    } else {
       Indicator.variable = null
    }
    IndicatorData.push(Indicator)
    })
 ;
 
 
 export default IndicatorData;